version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - binary: securae
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.Version={{ .Version }}
      - -X main.BuildDate={{ .Date }}
      - -X main.GitBranch={{ .Branch }}
      - -X main.GitCommit={{ .ShortCommit }} 

archives:
  - format: binary

checksum:
  name_template: 'SHA256SUMS'
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
